name: Release Publish

on:
  push:
    tags:
      - 'v*'
    #    branches:
    #      - workflow-test
#  pull_request:
#    branches:
#      - workflow-test


jobs:
  Note-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run cmd Test
        run: |
          echo `/usr/bin/git rev-list --tags --skip=0 --max-count=1`
          echo `/usr/bin/git describe --abbrev=0 --tags`

      - name: Generate list using Markdown
        run: |
          echo "## Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.3.0
        with:
          configuration: "change-log-config.json"
          owner: "wswenyue"
          ignorePreReleases: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Echo Configuration without Checkout Changelog
        env:
          CHANGELOG: ${{ steps.build_changelog.outputs.changelog }}
        run: |
          echo "CHANGELOG"
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "### ChangeLog! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.build_changelog.outputs.changelog }} >> $GITHUB_STEP_SUMMARY # changelog

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
        #          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}